print("hello ahah")
print("lekrjhfgnikgnbvjkchtkjgvbvn xjk;drn f,nklgf,jhfnjfghnjnjkgjkndjfnkjf,l,cslhlckg,kfcnnbkjcnbcnkblckb dfkbnkcnvkjcjnkbcv jkbncvkjnjcmxcmxiphkfg,kohnjdohndjhndighdingxnkjvnbcjnbckjbnckjnbcjbnckjnjcknbkj nbkj nbjfckvlbbj lvjvjbkckvj")
